/* A2 changes only the website presentation. No frame-content access, answer capture or form POST. */
(() => {
'use strict'; if(window.BW_AGENT_PAGE_A2) return;
const body=document.body,root=document.documentElement,frame=document.getElementById('agent-booking-form');
if(!body.classList.contains('agents-page')||!frame) return;
const labels={
en:{email:'Email Head Office',start:'Start your request',guide:'A little planning. A warm welcome.',step1:'Agent & group',detail1:'Your agency and passenger details.',step2:'Dining or catering',detail2:'Locations, dates and menu choices.',step3:'Up to five bookings',detail3:'One submission for the same group.',assistance:'Speak to our booking team',focus:'Focus view',exit:'Exit focus view',original:'Original form colours',matched:'Use site colours',appearance:'Display styling only. Your original booking form and its questions stay the same.'},
hi:{email:'????? ???????? ?? ???? ????',start:'अपना अनुरोध शुरू करें',guide:'थोड़ी तैयारी। गर्मजोशी से स्वागत।',step1:'एजेंट और समूह',detail1:'आपकी एजेंसी और यात्रियों की जानकारी।',step2:'भोजन या कैटरिंग',detail2:'स्थान, तारीखें और मेन्यू का चयन।',step3:'अधिकतम पाँच बुकिंग',detail3:'एक ही समूह के लिए एक फ़ॉर्म।',assistance:'हमारी बुकिंग टीम से बात करें',focus:'फ़ोकस दृश्य',exit:'फ़ोकस दृश्य से बाहर आएँ',original:'फ़ॉर्म के मूल रंग',matched:'वेबसाइट के रंग',appearance:'केवल दिखावट बदली है। आपका मूल बुकिंग फ़ॉर्म और उसके प्रश्न वही हैं।'},
ta:{email:'????? ?????????????? ??????????',start:'உங்கள் கோரிக்கையைத் தொடங்குங்கள்',guide:'சிறு திட்டமிடல். அன்பான வரவேற்பு.',step1:'முகவரும் குழுவும்',detail1:'உங்கள் நிறுவனம் மற்றும் பயணிகளின் விவரங்கள்.',step2:'உணவகம் அல்லது கேட்டரிங்',detail2:'இடங்கள், தேதிகள் மற்றும் உணவுத் தேர்வுகள்.',step3:'ஐந்து முன்பதிவுகள் வரை',detail3:'ஒரே குழுவுக்கு ஒரு படிவம்.',assistance:'முன்பதிவு குழுவைத் தொடர்புகொள்ளுங்கள்',focus:'கவனக்குவிப்பு காட்சி',exit:'வழக்கமான காட்சிக்குத் திரும்பவும்',original:'படிவத்தின் அசல் நிறங்கள்',matched:'தளத்தின் நிறங்களைப் பயன்படுத்தவும்',appearance:'காட்சியமைப்பு மட்டுமே மாறுகிறது. அசல் படிவமும் கேள்விகளும் மாறாது.'},
id:{email:'Email kantor pusat',start:'Mulai permintaan Anda',guide:'Sedikit persiapan. Sambutan hangat.',step1:'Agen & rombongan',detail1:'Detail agen dan jumlah peserta.',step2:'Bersantap atau katering',detail2:'Lokasi, tanggal, dan pilihan menu.',step3:'Hingga lima pemesanan',detail3:'Satu pengajuan untuk rombongan yang sama.',assistance:'Hubungi tim pemesanan',focus:'Tampilan fokus',exit:'Keluar dari tampilan fokus',original:'Warna asli formulir',matched:'Gunakan warna situs',appearance:'Hanya tampilan yang disesuaikan. Formulir asli dan pertanyaannya tetap sama.'},
th:{email:'????????????????????',start:'เริ่มคำขอของคุณ',guide:'เตรียมพร้อมสักนิด เพื่อการต้อนรับที่อบอุ่น',step1:'เอเจนต์และกลุ่ม',detail1:'ข้อมูลบริษัทและจำนวนผู้ร่วมกลุ่ม',step2:'ทานที่ร้านหรือจัดเลี้ยง',detail2:'สถานที่ วันที่ และเมนูที่ต้องการ',step3:'สูงสุดห้าการจอง',detail3:'ส่งครั้งเดียวสำหรับกลุ่มเดียวกัน',assistance:'ติดต่อทีมรับจอง',focus:'มุมมองโฟกัส',exit:'ออกจากมุมมองโฟกัส',original:'สีดั้งเดิมของแบบฟอร์ม',matched:'ใช้สีของเว็บไซต์',appearance:'ปรับเฉพาะการแสดงผล แบบฟอร์มต้นฉบับและคำถามยังเหมือนเดิม'}
};
const focus=document.querySelector('[data-agent-focus]'),colours=document.querySelector('[data-agent-colours]');
let previousY=0,loads=0;frame.addEventListener('load',()=>loads++);
function render(){const t=labels[root.lang]||labels.en;document.querySelectorAll('[data-agent-enhance]').forEach(el=>{const value=t[el.dataset.agentEnhance];if(value&&el.textContent!==value)el.textContent=value;});focus.querySelector('span').textContent=t[body.classList.contains('a2-focus')?'exit':'focus'];colours.querySelector('span').textContent=t[body.classList.contains('a2-original-form')?'matched':'original'];}
function setFocus(enabled){if(enabled===body.classList.contains('a2-focus')) return;if(enabled) previousY=scrollY;body.classList.toggle('a2-focus',enabled);focus.setAttribute('aria-pressed',String(enabled));render();requestAnimationFrame(()=>{window.scrollTo({top:enabled?0:previousY,behavior:'instant'});focus.focus({preventScroll:true});window.dispatchEvent(new Event('resize'));});}
focus.addEventListener('click',()=>setFocus(!body.classList.contains('a2-focus')));
colours.addEventListener('click',()=>{const active=body.classList.toggle('a2-original-form');colours.setAttribute('aria-pressed',String(active));render();});
document.querySelector('[data-agent-start]')?.addEventListener('click',event=>{event.preventDefault();const target=document.getElementById('agent-form');target.scrollIntoView({block:'start',behavior:root.classList.contains('motion-paused')||matchMedia('(prefers-reduced-motion:reduce)').matches?'instant':'smooth'});target.focus({preventScroll:true});});
document.addEventListener('keydown',event=>{if(event.key==='Escape'&&body.classList.contains('a2-focus'))setFocus(false);});
document.addEventListener('bw:language',render);window.addEventListener('pageshow',render);render();
window.BW_AGENT_PAGE_A2={version:'A2',get frameLoads(){return loads;},get focusView(){return body.classList.contains('a2-focus');},get originalColours(){return body.classList.contains('a2-original-form');},formModified:false,answersCaptured:false,themeTechnique:'CSS display filter on the original cross-origin embed; reversible; no internal restyling',setFocus};
})();