/* C1: scoped browse-only Club categories. No orders, prices, bookings or shared page edits. */
(()=>{'use strict';const section=document.querySelector('[data-club-menu-c1]');if(!section||window.BW_CLUB_MENU_C1)return;
const tabs=[...section.querySelectorAll('[data-cm1-tab]')],panels=[...section.querySelectorAll('.cm1-panel')],list=section.querySelector('.cm1-tabs'),small=matchMedia('(max-width:760px)');
const copy={en:{promos:'HOT PROMOS',food:'FOOD',beverage:'BEVERAGE',shisha:'SHISHA',explore:'EXPLORE THE MENUS'},hi:{promos:'खास ऑफ़र',food:'भोजन',beverage:'पेय',shisha:'शीशा',explore:'मेन्यू देखें'},ta:{promos:'சிறப்புச் சலுகைகள்',food:'உணவு',beverage:'பானங்கள்',shisha:'ஷிஷா',explore:'மெனுக்களைப் பாருங்கள்'},id:{promos:'PROMO SPESIAL',food:'MAKANAN',beverage:'MINUMAN',shisha:'SHISHA',explore:'JELAJAHI MENU'},th:{promos:'โปรโมชันพิเศษ',food:'อาหาร',beverage:'เครื่องดื่ม',shisha:'ชิชา',explore:'เลือกดูเมนู'}};
let selected='promos',frame=0;const off=()=>matchMedia('(prefers-reduced-motion:reduce)').matches||document.documentElement.classList.contains('motion-paused');
function render(){const lang=copy[document.documentElement.lang]?document.documentElement.lang:'en';section.querySelectorAll('[data-cm1-copy]').forEach(e=>{const t=copy[lang][e.dataset.cm1Copy];if(t&&e.textContent!==t)e.textContent=t;});list.setAttribute('aria-orientation',small.matches?'horizontal':'vertical');}
function show(id,{focus=false,scroll=false,hash=false}={}){const active=tabs.find(t=>t.dataset.cm1Tab===id);if(!active)return;selected=id;tabs.forEach(t=>{const on=t===active;t.setAttribute('aria-selected',String(on));t.tabIndex=on?0:-1;});panels.forEach(p=>{p.hidden=p.id!=='cm1-panel-'+id;p.classList.remove('is-entering');});const panel=section.querySelector('#cm1-panel-'+id);if(!off()){void panel.offsetWidth;panel.classList.add('is-entering');}if(focus)active.focus({preventScroll:true});if(small.matches){const left=active.offsetLeft,right=left+active.offsetWidth;if(left<list.scrollLeft)list.scrollLeft=left;else if(right>list.scrollLeft+list.clientWidth)list.scrollLeft=right-list.clientWidth;}
if(hash){try{const url=new URL(location.href);url.hash='cm1-panel-'+id;history.replaceState(null,'',url);}catch{}}
if(scroll){cancelAnimationFrame(frame);frame=requestAnimationFrame(()=>{const header=document.querySelector('header')?.getBoundingClientRect().height||96;const y=section.getBoundingClientRect().top;if(y<header-20)window.scrollTo({top:scrollY+y-header-12,behavior:off()?'auto':'smooth'});});}}
function fromHash(scroll=false){const h=location.hash;if(/^#cm1-panel-(promos|food|beverage|shisha)$/.test(h))show(h.split('-').at(-1),{scroll});else if(h==='#offers'||h==='#menu')show('promos',{scroll});else if(h==='#club-inline-menu'||h==='#menu-0')show('beverage',{scroll});else if(h==='#menu-1')show('shisha',{scroll});}
tabs.forEach((tab,i)=>{tab.addEventListener('click',()=>show(tab.dataset.cm1Tab,{scroll:true,hash:true}));tab.addEventListener('keydown',e=>{if(e.altKey||e.ctrlKey||e.metaKey)return;let next;const horizontal=small.matches;if(e.key===(horizontal?'ArrowRight':'ArrowDown'))next=(i+1)%tabs.length;if(e.key===(horizontal?'ArrowLeft':'ArrowUp'))next=(i+tabs.length-1)%tabs.length;if(e.key==='Home')next=0;if(e.key==='End')next=tabs.length-1;if(next!==undefined){e.preventDefault();show(tabs[next].dataset.cm1Tab,{focus:true,hash:true});}});});
section.addEventListener('animationend',e=>{if(e.target.classList.contains('cm1-panel'))e.target.classList.remove('is-entering');});
small.addEventListener('change',render);document.addEventListener('bw:language',render);window.addEventListener('hashchange',()=>fromHash(true));render();show(selected);fromHash();
window.BW_CLUB_MENU_C1={version:'C1',scope:'Club Bottle Promos and menus only',get selected(){return selected},categories:tabs.map(t=>t.dataset.cm1Tab),sourceArtworkUnchanged:true,select:show};
})();
