/* Experience 04. UI only: no automatic bookings, messages, feed scraping or analytics. */
(() => {
'use strict';
const root=document.documentElement,reduce=matchMedia('(prefers-reduced-motion: reduce)');
const motionOff=()=>reduce.matches||root.classList.contains('motion-paused');
const toggles=[...document.querySelectorAll('[data-appearance-toggle]')];
function applyTheme(theme,save=false){theme=theme==='light'?'light':'dark';root.dataset.appearance=theme;root.style.colorScheme=theme;const next=theme==='dark'?'White view':'Dark view';toggles.forEach(b=>{b.setAttribute('aria-label','Switch to '+next);b.setAttribute('aria-pressed',String(theme==='light'));b.querySelector('.appearance-label').textContent=next;b.querySelector('.appearance-icon').textContent=theme==='dark'?'☀':'☾';});document.querySelector('meta[name="theme-color"]')?.setAttribute('content',theme==='dark'?'#0b0b0d':'#faf7f1');if(save)try{localStorage.setItem('bw-appearance',theme);}catch{}document.dispatchEvent(new CustomEvent('bw:appearance',{detail:{theme}}));}
toggles.forEach(b=>b.addEventListener('click',()=>applyTheme(root.dataset.appearance==='light'?'dark':'light',true)));applyTheme(root.dataset.appearance);window.addEventListener('storage',e=>{if(e.key==='bw-appearance')applyTheme(e.newValue);});
const details=[...document.querySelectorAll('.stat-detail')];
details.forEach(d=>{let timer;const close=()=>{clearTimeout(timer);timer=setTimeout(()=>{if(!d.contains(document.activeElement))d.open=false;},180);};d.addEventListener('pointerenter',e=>{if(e.pointerType==='touch')return;clearTimeout(timer);d.open=true;});d.addEventListener('pointerleave',e=>{if(e.pointerType!=='touch')close();});d.addEventListener('toggle',()=>{if(d.open)details.forEach(other=>{if(other!==d&&other.open)other.open=false;});});d.addEventListener('focusout',()=>setTimeout(()=>{if(!d.contains(document.activeElement)&&!d.matches(':hover'))d.open=false;},0));});
document.addEventListener('click',e=>details.forEach(d=>{if(d.open&&!d.contains(e.target))d.open=false;}));document.addEventListener('keydown',e=>{if(e.key==='Escape')details.forEach(d=>{if(d.open){d.open=false;d.querySelector('summary').focus();}});});
const stages=[...document.querySelectorAll('.soundstage-art')];if('IntersectionObserver'in window){const observer=new IntersectionObserver(entries=>entries.forEach(e=>e.target.classList.toggle('in-motion-view',e.isIntersecting&&!document.hidden)),{threshold:.08});stages.forEach(s=>observer.observe(s));}else stages.forEach(s=>s.classList.add('in-motion-view'));
document.addEventListener('visibilitychange',()=>stages.forEach(s=>{const r=s.getBoundingClientRect();s.classList.toggle('in-motion-view',!document.hidden&&r.bottom>0&&r.top<innerHeight);}));
const reels=[...document.querySelectorAll('.reel-card')];
function unload(card,announce=true){const player=card.querySelector('.reel-player');player.replaceChildren();player.hidden=true;card.querySelector('.reel-cover').hidden=false;card.querySelector('[data-close-reel]').hidden=true;card.classList.remove('is-playing');if(announce)card.querySelector('.reel-state').textContent='Player closed. The original Reel remains available.';}
reels.forEach(card=>{const button=card.querySelector('[data-load-reel]'),player=card.querySelector('.reel-player');button.addEventListener('click',()=>{const id=card.dataset.reel;if(!/^[A-Za-z0-9_-]{5,30}$/.test(id))return;reels.filter(r=>r!==card&&r.classList.contains('is-playing')).forEach(r=>unload(r));const frame=document.createElement('iframe');frame.src='https://www.instagram.com/reel/'+id+'/embed/';frame.title=card.querySelector('h3').textContent+' — Instagram Reel';frame.allow='encrypted-media; picture-in-picture; fullscreen';frame.allowFullscreen=true;frame.loading='eager';frame.referrerPolicy='strict-origin-when-cross-origin';player.replaceChildren(frame);player.hidden=false;card.querySelector('.reel-cover').hidden=true;card.querySelector('[data-close-reel]').hidden=false;card.classList.add('is-playing');card.querySelector('.reel-state').textContent='Instagram player requested. If the video does not play, use Open original.';});card.querySelector('[data-close-reel]').addEventListener('click',()=>{unload(card);button.focus({preventScroll:true});});});
if('IntersectionObserver'in window){const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(!e.isIntersecting&&e.target.classList.contains('is-playing'))unload(e.target);}),{rootMargin:'350px 0px'});reels.forEach(r=>observer.observe(r));}
window.addEventListener('pagehide',()=>reels.forEach(r=>unload(r,false)));
window.BW_EXPERIENCE={revision:4,get appearance(){return root.dataset.appearance;},get statsOpen(){return details.filter(d=>d.open).map(d=>d.id);},get motionOff(){return motionOff();},reelCount:reels.length,get activeReels(){return reels.filter(r=>r.classList.contains('is-playing')).length;}};
})();
