/* H7: H6 eye drawing and animation clock unchanged. Static logo never replaced. */
(()=>{'use strict';const root=document.documentElement,header=document.querySelector('.bw-shared-header');if(!header||window.BW_HEADER_H7)return;const links=[...header.querySelectorAll('.bw-night-target')],reduce=matchMedia('(prefers-reduced-motion:reduce)');let canvas=null,ctx=null,field=null,raf=0,queueId=0,lastFrame=0,lastTick=0,elapsed=0,painted=0,lastPlacement=null,eyeWidth=140,eyeHeight=80,eyeRX=50,eyeRY=22,intensity=0,hover=false,light=root.dataset.appearance==='light';
const off=()=>reduce.matches||root.classList.contains('motion-paused')||document.hidden||!field||field.hidden||Boolean(navigator.connection?.saveData);
function locate(){queueId=0;const a=links.find(l=>l.offsetWidth&&l.closest('.desktop-nav'))||links.find(l=>l.offsetWidth);if(!a){links.forEach(l=>l.querySelector('.bw-spectrum-field').hidden=true);field=null;lastPlacement=null;sync();return;}field=a.querySelector('.bw-spectrum-field');canvas=field.querySelector('canvas');ctx=canvas.getContext('2d');links.forEach(l=>l.querySelector('.bw-spectrum-field').hidden=l!==a);const r=a.querySelector('.bw-nav-label').getBoundingClientRect(),p=a.getBoundingClientRect(),h=header.getBoundingClientRect();if(!r.width){field.hidden=true;sync();return;}
eyeRX=Math.max(46,r.width/2+24);const cornerX=r.width/2+4,innerRX=eyeRX-5;eyeRY=Math.max(20,(r.height/2+4)/Math.pow(1-Math.pow(cornerX/innerRX,2),.675)+4);eyeWidth=Math.ceil(2*(eyeRX+22));eyeHeight=Math.ceil(2*(eyeRY+17));const x=r.x+r.width/2-p.x,y=r.y+r.height/2-p.y,dpr=Math.min(2,devicePixelRatio||1);if(canvas.width!==Math.round(eyeWidth*dpr)||canvas.height!==Math.round(eyeHeight*dpr)){canvas.width=Math.round(eyeWidth*dpr);canvas.height=Math.round(eyeHeight*dpr);canvas.style.width=eyeWidth+'px';canvas.style.height=eyeHeight+'px';}ctx?.setTransform(dpr,0,0,dpr,0,0);field.style.setProperty('--bw-spectrum-x',x.toFixed(2)+'px');field.style.setProperty('--bw-spectrum-y',y.toFixed(2)+'px');light=root.dataset.appearance==='light';lastPlacement={x,y,width:eyeWidth,height:eyeHeight,eyeRX,eyeRY,textWidth:r.width,textHeight:r.height,headerHeight:h.height,slotWidth:p.width,slotHeight:p.height,label:a.textContent.trim(),shape:'almond-eye'};a.classList.add('bw-eye-live');paint(elapsed);sync();}
function queue(){if(!queueId)queueId=requestAnimationFrame(locate);}
function colour(i,alpha=1){const f=(Math.sin(i*Math.PI*4)+1)/2;const rgb=light?[Math.round(182+30*f),Math.round(35+89*f),Math.round(22-6*f)]:[255,Math.round(46+160*f),Math.round(28+50*f)];return `rgba(${rgb.join(',')},${alpha})`;}
function eyePoint(a,pad=0){const s=Math.sin(a),c=Math.cos(a);return {x:c*(eyeRX+pad),y:Math.sign(s)*Math.pow(Math.abs(s),1.35)*(eyeRY+pad*.65)};}
function eyeStroke(start,end,pad=0){const steps=Math.max(3,Math.ceil(Math.abs(end-start)*28));ctx.beginPath();for(let j=0;j<=steps;j++){const p=eyePoint(start+(end-start)*j/steps,pad);if(j)ctx.lineTo(p.x,p.y);else ctx.moveTo(p.x,p.y);}}
function paint(t){if(!ctx||!field||field.hidden)return;painted++;ctx.clearRect(0,0,eyeWidth,eyeHeight);ctx.save();ctx.translate(eyeWidth/2,eyeHeight/2);
// H6 time coefficients and hover intensity are preserved; only the drawing path changes.
const beat=(Math.sin(t*5.8)+1)/2,drive=.22+.78*intensity,pulse=intensity*1.6*beat;
ctx.save();ctx.scale(1,(eyeRY+15)/(eyeRX+21));const halo=ctx.createRadialGradient(0,0,eyeRX*.65,0,0,eyeRX+21);halo.addColorStop(0,'rgba(255,100,20,0)');halo.addColorStop(.3,light?'rgba(196,42,20,.07)':`rgba(231,43,24,${.10+intensity*.10})`);halo.addColorStop(.63,light?'rgba(161,106,11,.07)':`rgba(255,178,47,${.10+intensity*.12})`);halo.addColorStop(1,'rgba(255,80,0,0)');ctx.fillStyle=halo;ctx.beginPath();ctx.arc(0,0,eyeRX+21,0,2*Math.PI);ctx.fill();ctx.restore();
for(let i=0;i<96;i++){const a=i/96*2*Math.PI-Math.PI/2,e=(Math.sin(i*.57-t*2.4)+Math.sin(i*.23+t*1.65)+2)/4,len=2+e*(4+intensity*10)+intensity*2.5*beat,p=eyePoint(a,pulse+3),q=eyePoint(a,pulse+3+len);ctx.lineWidth=.85+intensity*.4;ctx.strokeStyle=colour(i/96,.65+intensity*.3);ctx.beginPath();ctx.moveTo(p.x,p.y);ctx.lineTo(q.x,q.y);ctx.stroke();}
ctx.save();ctx.lineWidth=1.75+intensity*.7;for(let i=0;i<28;i++){const a=i/28*2*Math.PI+t*.14;ctx.strokeStyle=colour(i/28,.86);ctx.shadowColor=colour(i/28,.68);ctx.shadowBlur=light?1:3+intensity*4;eyeStroke(a+.017,a+2*Math.PI/28-.027,pulse);ctx.stroke();}ctx.restore();
for(let i=0;i<72;i++){const a=i/72*2*Math.PI-t*.10,p=eyePoint(a,-3);ctx.fillStyle=colour(i/72,.6);ctx.beginPath();ctx.arc(p.x,p.y,.46+intensity*.12,0,2*Math.PI);ctx.fill();}
for(let k=0;k<5;k++){ctx.beginPath();for(let i=0;i<=120;i++){const a=i/120*2*Math.PI,pad=Math.max(-5,-5+Math.sin(6*a+t*2.1+k*.3)*(1+drive*1.8)+k*.36),p=eyePoint(a,pad);if(i)ctx.lineTo(p.x,p.y);else ctx.moveTo(p.x,p.y);}ctx.closePath();ctx.lineWidth=.55;ctx.strokeStyle=colour(k/5+t*.02,light?.17:.22+intensity*.16);ctx.stroke();}ctx.restore();}
function tick(ts){raf=0;if(off()){lastTick=0;return;}if(ts-lastFrame>=32){const dt=Math.min(.09,lastTick?(ts-lastTick)/1000:.033);lastTick=ts;lastFrame=ts;intensity+=(Number(hover)-intensity)*Math.min(1,dt*8);elapsed+=dt*(1+intensity*2.1);paint(elapsed);}raf=requestAnimationFrame(tick);}
function sync(){if(raf)cancelAnimationFrame(raf);raf=0;lastTick=0;root.classList.toggle('bw-header-motion-off',document.hidden);if(off()){paint(elapsed);return;}raf=requestAnimationFrame(tick);}
links.forEach(a=>{a.addEventListener('pointerenter',()=>{hover=true;paint(elapsed);});a.addEventListener('pointerleave',()=>{hover=false;paint(elapsed);});a.addEventListener('focus',()=>{hover=true;paint(elapsed);});a.addEventListener('blur',()=>{hover=false;paint(elapsed);});});window.addEventListener('resize',queue,{passive:true});window.addEventListener('pageshow',queue);window.addEventListener('pagehide',()=>{if(raf)cancelAnimationFrame(raf);raf=0;});document.addEventListener('bw:language',queue);document.addEventListener('bw:headerlayout',queue);document.addEventListener('visibilitychange',sync);header.addEventListener('scroll',queue,true);reduce.addEventListener('change',sync);if('ResizeObserver'in window){const o=new ResizeObserver(queue);o.observe(header);links.forEach(a=>o.observe(a));}new MutationObserver(()=>{light=root.dataset.appearance==='light';sync();}).observe(root,{attributes:true,attributeFilter:['class','data-appearance']});new MutationObserver(queue).observe(header.querySelector('#bw-mobile-navigation'),{attributes:true,attributeFilter:['hidden']});document.fonts?.ready.then(queue);locate();window.BW_HEADER_H7={version:'H7',palette:'red-yellow-gold',get placement(){return lastPlacement},get phase(){return elapsed},get energy(){return intensity},get frames(){return painted},get running(){return !!raf},get paused(){return off()},scope:'Static shared header; unchanged H6 eye animation clock.'};})();