'use strict';
// No automatic bookings, no simulated success, no personal data in analytics events.
(() => {
 const config=window.BW_CONFIG||{branches:{},analytics:{enabled:false}};
 const $=(s,scope=document)=>scope.querySelector(s),$$=(s,scope=document)=>Array.from(scope.querySelectorAll(s));
 const toggle=$('.menu-toggle'),nav=$('#mobile-navigation');
 function closeNav(returnFocus=false){if(!nav||!toggle)return;nav.hidden=true;toggle.setAttribute('aria-expanded','false');toggle.setAttribute('aria-label','Open navigation');if(returnFocus)toggle.focus();}
 if(toggle&&nav){toggle.addEventListener('click',()=>{const opening=nav.hidden;nav.hidden=!opening;toggle.setAttribute('aria-expanded',String(opening));toggle.setAttribute('aria-label',opening?'Close navigation':'Open navigation');});$$('a',nav).forEach(a=>a.addEventListener('click',()=>closeNav()));document.addEventListener('click',ev=>{if(!nav.hidden&&!nav.contains(ev.target)&&!toggle.contains(ev.target))closeNav();});document.addEventListener('keydown',ev=>{if(ev.key==='Escape'&&!nav.hidden)closeNav(true);});window.addEventListener('resize',()=>{if(window.innerWidth>1000)closeNav();},{passive:true});}
 const galleryButtons=$$('[data-gallery-filter]'),cards=$$('[data-gallery-card]');
 function filterGallery(id){if(!galleryButtons.some(b=>b.dataset.galleryFilter===id))id='all';galleryButtons.forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.galleryFilter===id)));cards.forEach(c=>c.hidden=id!=='all'&&c.dataset.galleryBranch!==id);const count=cards.filter(c=>!c.hidden).length;const status=$('#gallery-status');if(status)status.textContent=id==='club'?'See current Club photographs on Instagram.':`${count} photograph${count===1?'':'s'}`;const note=$('#club-gallery-note');if(note)note.hidden=id!=='club';}
 if(galleryButtons.length){galleryButtons.forEach(b=>b.addEventListener('click',()=>filterGallery(b.dataset.galleryFilter)));filterGallery(new URLSearchParams(location.search).get('branch')||'all');}
 const dialog=$('#photo-dialog'),large=$('#photo-large');let activePhoto=0,photoFocus=null;
 const visiblePhotos=()=>$$('[data-photo]').filter(b=>!b.closest('[data-gallery-card]')?.hidden);
 function showPhoto(index){const list=visiblePhotos();if(!list.length||!large)return;activePhoto=(index+list.length)%list.length;const button=list[activePhoto];large.src=button.dataset.photo;large.alt=button.dataset.caption;$('#photo-title').textContent=button.dataset.caption;$('#photo-count').textContent=`${activePhoto+1} / ${list.length}`;}
 if(dialog&&large){$$('[data-photo]').forEach(b=>b.addEventListener('click',()=>{photoFocus=b;showPhoto(visiblePhotos().indexOf(b));dialog.showModal();document.body.classList.add('modal-open');}));$('[data-close-photo]').addEventListener('click',()=>dialog.close());$('[data-photo-prev]').addEventListener('click',()=>showPhoto(activePhoto-1));$('[data-photo-next]').addEventListener('click',()=>showPhoto(activePhoto+1));dialog.addEventListener('close',()=>{document.body.classList.remove('modal-open');photoFocus?.focus({preventScroll:true});});dialog.addEventListener('click',ev=>{if(ev.target===dialog){const r=dialog.getBoundingClientRect();if(ev.clientX<r.left||ev.clientX>r.right||ev.clientY<r.top||ev.clientY>r.bottom)dialog.close();}});dialog.addEventListener('keydown',ev=>{if(ev.key==='ArrowLeft'){ev.preventDefault();showPhoto(activePhoto-1);}if(ev.key==='ArrowRight'){ev.preventDefault();showPhoto(activePhoto+1);}});}
 $$('[data-pdf-preview]').forEach(button=>button.addEventListener('click',()=>{const target=document.getElementById(button.getAttribute('aria-controls'));if(!target)return;const opening=target.hidden;target.hidden=!opening;button.setAttribute('aria-expanded',String(opening));button.textContent=opening?'Close preview':'Preview here';if(opening&&!$('iframe',target)){const frame=document.createElement('iframe');frame.title=button.dataset.pdfTitle+' PDF preview';frame.src=button.dataset.pdfPreview+'#view=FitH';frame.loading='lazy';const note=document.createElement('p');note.className='small';note.textContent='If the PDF is not displayed by your browser, use “Open full menu” above to read it in your device’s PDF viewer.';target.append(frame,note);}}));
 const search=$('#menu-search'),menuItems=$$('[data-menu-item]');let menuFilter='all';
 function filterMenu(){const query=(search?.value||'').trim().toLowerCase();let count=0;menuItems.forEach(item=>{const match=item.dataset.search.includes(query)&&(menuFilter==='all'||item.dataset.vegetarian==='true');item.hidden=!match;if(match)count++;});$$('[data-menu-section]').forEach(section=>{section.hidden=!$$('[data-menu-item]',section).some(i=>!i.hidden);const anchor=$(`.menu-directory a[href="#${section.id}"]`);if(anchor)anchor.hidden=section.hidden;});const status=$('#menu-result-count');if(status)status.textContent=`${count} dish${count===1?'':'es'}${query?' matching your search':''}`;const empty=$('#menu-no-results');if(empty)empty.hidden=count!==0;}
 if(search){search.addEventListener('input',filterMenu);$$('[data-menu-filter]').forEach(b=>b.addEventListener('click',()=>{menuFilter=b.dataset.menuFilter;$$('[data-menu-filter]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));filterMenu();}));filterMenu();}$$('[data-print-menu]').forEach(b=>b.addEventListener('click',()=>window.print()));
 const form=$('#reservation-form'),branchInput=$('#book-branch'),dateInput=$('#book-date');
 function localNow(timezone){const parts=Object.fromEntries(new Intl.DateTimeFormat('en-GB',{timeZone:timezone,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(new Date()).map(p=>[p.type,p.value]));return {date:`${parts.year}-${parts.month}-${parts.day}`,time:`${parts.hour}:${parts.minute}`};}
 function syncDate(){if(!dateInput)return;const branch=config.branches[branchInput.value];if(branch)dateInput.min=localNow(branch.timezone).date;else dateInput.removeAttribute('min');}
 if(form&&branchInput){const queryBranch=new URLSearchParams(location.search).get('branch');if(queryBranch&&config.branches[queryBranch])branchInput.value=queryBranch;syncDate();branchInput.addEventListener('change',syncDate);const result=$('#reservation-result'),error=$('#reservation-error');form.addEventListener('input',()=>{result.hidden=true;error.hidden=true;});form.addEventListener('change',()=>{result.hidden=true;error.hidden=true;});
 form.addEventListener('submit',ev=>{ev.preventDefault();result.hidden=true;error.hidden=true;const branch=config.branches[branchInput.value];if(!branch){error.textContent='Please choose a location.';error.hidden=false;branchInput.focus();return;}const name=$('#book-name').value.trim().replace(/\s+/g,' '),date=dateInput.value,time=$('#book-time').value,guests=Number($('#book-guests').value),occasion=$('#book-occasion').value,notes=$('#book-notes').value.trim();const now=localNow(branch.timezone);if(!name||!date||!time||!Number.isInteger(guests)||guests<1||guests>500){error.textContent='Please complete the required fields with a valid name, date, time and guest count.';error.hidden=false;return;}if(date<now.date||(date===now.date&&time<now.time)){error.textContent='Please choose a date and time that have not passed in the restaurant’s local time.';error.hidden=false;dateInput.focus();return;}const message=`Hello Bollywood ${branch.name},\nI would like to enquire about: ${occasion}.\n\nName: ${name}\nDate: ${date}\nPreferred time: ${time} (${branch.timezone} local time)\nGuests: ${guests}${notes?'\nRequests: '+notes:''}\n\nPlease confirm availability. This is an enquiry, not a confirmed booking.`;$('#reservation-message').textContent=message;const handoff=$('#reservation-handoff');handoff.href=branch.whatsapp?'https://wa.me/'+branch.whatsapp+'?text='+encodeURIComponent(message):'tel:+'+branch.phone;handoff.textContent=branch.whatsapp?'Open WhatsApp ↗':'Call '+branch.phoneDisplay;if(branch.whatsapp)handoff.setAttribute('target','_blank');else handoff.removeAttribute('target');handoff.dataset.track=branch.whatsapp?'whatsapp_enquiry':'call_enquiry';$('#reservation-result-title').textContent='Your enquiry is ready — not yet sent.';$('#reservation-result-note').textContent=branch.whatsapp?`Open WhatsApp and press Send to share this with ${branch.contactLabel}. Please wait for the team to confirm your reservation.`:`Call ${branch.phoneDisplay} to make your enquiry. This site does not assume that the number accepts WhatsApp. Your reservation is not confirmed until the restaurant agrees.`;$('#copy-feedback').textContent='';result.hidden=false;result.scrollIntoView({block:'nearest',behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'});});
 $('#copy-enquiry').addEventListener('click',async()=>{try{if(!navigator.clipboard?.writeText)throw new Error('Clipboard unavailable');await navigator.clipboard.writeText($('#reservation-message').textContent);$('#copy-feedback').textContent='Enquiry copied. Nothing has been sent.';}catch{$('#copy-feedback').textContent='Select the enquiry text above and copy it using your device controls.';}});}
 window.BW_EVENTS=[];document.addEventListener('click',event=>{const target=event.target.closest('[data-track]');if(!target)return;const detail={action:target.dataset.track,branch:document.body.dataset.branch||branchInput?.value||'company',page:location.pathname};window.BW_EVENTS.push(detail);if(window.BW_EVENTS.length>200)window.BW_EVENTS.shift();document.dispatchEvent(new CustomEvent('bw:interaction',{detail}));if(config.analytics?.enabled&&typeof window.gtag==='function')window.gtag('event',detail.action,{branch:detail.branch,page_path:detail.page});});
})();
